Научить routerd форвардить отдельные части ответов, а не всю пачку
autumncoffee/routerd pull request #1
Opened 2020-11-12 15:47 UTC by sutyrin

2020-11-12 16:26 UTC, kainwinterheart commented on src/routerd_lib/request.hpp
> +            return OutgoingRequest_;
Please use `Out()` instead.

2020-11-17 12:37 UTC, kainwinterheart requested changes

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                    auto matching_part = outgoing_request.PartByName(service.SendRawOutputOf);
`matching_part` -> `matchingPart`

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                    auto &&outgoing_request = request->GetOutGoingRequest();
`auto &&outgoing_request` -> `auto&& outgoingRequest`

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +    void TRouterDProxyHandler::print_outgoing_request(std::shared_ptr<TRouterDRequest> request) const{
`TRouterDProxyHandler::print_outgoing_request` -> `TRouterDProxyHandler::PrintOutgoingRequest `

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +        auto &outgoing_request = request->GetOutGoingRequest();
`auto &outgoing_request` -> `auto& outgoingRequest`

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +        for (auto && [header, values] : outgoing_request.Headers()) {
`for (auto && [header, values]` -> `for (auto&& [header, values]`

And please add empty line before "for".

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +            if(values.size() == 1) {
`if(values` -> `if (values`

Please add empty line before "if".

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +            } else if (values.size() >= 2 ) {
Please add empty line before "else".

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +            } else {
Empty line before "else" here too.

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                for (auto && value : values) {
`for (auto && value` -> `for (auto&& value`

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +        for (auto &&part : outgoing_request.Parts()) {
`for (auto &&part` -> `for (auto&& part`

And empty line before "for", of course.

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +            NHTTP::THeaderParams ContentDispositionParams;
`ContentDisposition ` -> `contentDisposition`, `ContentDispositionParams` -> `contentDispositionParams`

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                                    ContentDisposition, ContentDispositionParams);
Formatting.

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +            for (auto[key, value]: ContentDispositionParams) {
Missing empty line and space after "auto".

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +            for (auto[name, value] : part.Headers()) {
Missing empty line and space again.

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                for (auto v : value) {
Missing empty line.

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +            std::cerr << "  [content]" << std::string(part.Content(), part.ContentLength())
Missing empty line between "}" and following expression.

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +        std::cerr << "=== end of parts ===" << std::endl;
Missing empty line and following expression again.

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                if(!service.SendRawOutputOf.empty() && !request->GetOutGoingRequest().PartByName(service.SendRawOutputOf)) {
`if(!service.` -> `if (!service.`

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                    else { // should not happen: we've checked it above
"}" and "else" should be on the same line, separated by empty line from previous expression.

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/main.cpp
> +                    if(compiledGraph.ReverseTree[name].size() > 0) {
Empty line before "if".

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/main.cpp
> +                    if (compiledGraph.Tree[name].size() > 0) {
Empty line before "if".

2020-11-17 12:37 UTC, kainwinterheart commented on src/routerd_lib/main.cpp
> +                        router, std::forward<NHTTPServer::TClient::TArgs::TRequestFactory>(requestFactory));
Please do not change formatting of existing code just for the sake of changing formatting.

2020-11-17 13:59 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +            } else if (values.size() >= 2 ) {
Also, extra space after "2" needs to be removed.

2020-11-17 13:59 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                for (auto && value : values) {
Extra space after "2".

2020-11-17 14:41 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                 && Graph.Services.at(serviceName).SaveAs == std::string("output"))
This is incredibly kludgy and unnecessary in general. Just call `ProcessServiceResponse` with `service.Save` as part name in `Iter` in that case. And do not forget to call `ServiceReplied` with original service name after that, the same way as in multipart/x-ac-routerd case.

2020-11-17 15:46 UTC, sutyrin commented on src/routerd_lib/handlers/proxy.cpp
> +                if (!service.SendRawOutputOf.empty() && !request->GetOutGoingRequest().PartByName(service.SendRawOutputOf)) {
Выходит, эту проверку можно теперь убрать?

2020-11-17 15:51 UTC, kainwinterheart requested changes

2020-11-17 15:51 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +    void TRouterDProxyHandler::printOutgoingRequest(std::shared_ptr<TRouterDRequest> request) const{
`printOutgoingRequest` -> `PrintOutgoingRequest`.

2020-11-17 15:51 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +        auto& outgoing_request = request->GetOutGoingRequest();
`outgoing_request` -> `outgoingRequest`

2020-11-17 15:51 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +            std::string ContentDisposition;
`ContentDisposition` -> `contentDisposition`

2020-11-17 15:51 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +            NHTTP::THeaderParams ContentDispositionParams;
`ContentDispositionParams` -> `contentDispositionParams`

2020-11-17 15:51 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                if (!service.SendRawOutputOf.empty() && !request->GetOutGoingRequest().PartByName(service.SendRawOutputOf)) {
This case seems to be redundant here because `SendRawOutputOf` is already in dependencies and is checked prior to that line.

2020-11-17 15:51 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                    if (matchingPart) {
Please add empty line before "if".

2020-11-17 15:51 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                    } else { // should not happen: we've checked it above
Please add empty line before "} else {".

2020-11-17 15:51 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                        std::cerr << "raw output part not found, issuing 500" << std::endl;
This message seems important, let's print it regardless of AC_DEBUG_ROUTERD_PROXY.

2020-11-17 15:51 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                    } else {
Please add empty line before "} else {".

2020-11-17 15:51 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +        if (serviceName == std::string("output") && !request->IsResponseSent()
Please add empty line before "if".

2020-11-17 15:51 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +        ) { // TODO
Weird formatting, it should be as it was: `if ((serviceName == std::string("output")) && !request->IsResponseSent()) {`

2020-11-17 15:51 UTC, kainwinterheart commented on src/routerd_lib/main.cpp
> +//                if (compiledGraph.Services.count(service.Name) > 0) {
Consider uncommenting it back please.

2020-11-17 15:51 UTC, kainwinterheart commented on src/routerd_lib/main.cpp
> +                        ) {
Either
```
if (
    compiledGraph.Tree.count(name) == 0
    || compiledGraph.Tree[name].count(service.SendRawOutputOf) == 0
) {
```

or
```
if (compiledGraph.Tree.count(name) == 0 || compiledGraph.Tree[name].count(service.SendRawOutputOf) == 0) {
```

2020-11-17 15:54 UTC, kainwinterheart commented on src/routerd_lib/handlers/proxy.cpp
> +                if (!service.SendRawOutputOf.empty() && !request->GetOutGoingRequest().PartByName(service.SendRawOutputOf)) {
Да.

2020-11-17 16:51 UTC, merged